version: "2"

services:

    database:
        image: mysql:5.7.20
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD"
        volumes:
            - /mydata/mysql:/var/lib/mysql
            - ./config:/etc/mysql/mysql.conf.d
